version: '3'
services:
  mysql:
    image: mysql:5.7.24
    container_name: mysql
    ports:
      - "3306:3306"
    networks: 
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=xinqing
      - MYSQL_USER=xinqing
      - MYSQL_PASSWORD=xinqing
      
  tomcat:
    image: tomcat:8.5.35-jre8-alpine
    container_name: tomcat
    ports:
      - "8080:8080"
    networks: 
      - backend
    volumes:
      - ./webapps:/usr/local/tomcat/webapps
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "8000:80"
    networks: 
      - backend
    environment:
      - PMA_HOST=mysql

networks: 
  backend:
    
    
